### ISSUE TITLE
HTTP 404 on http://tapintomuseums.org/TourML

### ISSUE THREAD

**Issue by IllyaMoskvin** [IMAmuseum/tap-cms#46]
Each TourML `.xml` file declares that `xmlns:tourml="http://tapintomuseums.org/TourML"` and `xsi:schemaLocation="http://tapintomuseums.org/TourML TourML.xsd"`. Both URIs result in an HTTP 404 Response.

**Comment by kjaebker** [comment]
may take a minute for the files to show up in the proper location so no 404s occur.
